(cl:in-package ros_its_msgs-msg)
(cl:export '(CAR_NAME-VAL
          CAR_NAME
          STATION_ID-VAL
          STATION_ID
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE_ALTITUDEVALUE-VAL
          ALTITUDE_ALTITUDEVALUE
          HEADING_HEADINGVALUE-VAL
          HEADING_HEADINGVALUE
          SPEED_SPEEDVALUE-VAL
          SPEED_SPEEDVALUE
          DRIVEDIRECTION-VAL
          DRIVEDIRECTION
          STEERINGWHEELANGLE_STEERINGWHEELANGLEVALUE-VAL
          STEERINGWHEELANGLE_STEERINGWHEELANGLEVALUE
          GASPEDALPERCENT_VALUE-VAL
          GASPEDALPERCENT_VALUE
          BRAKEPEDALPERCENT_VALUE-VAL
          BRAKEPEDALPERCENT_VALUE
))