# IDs

string car_name
string Station_ID

# Reference Position
#int32 latitude
#int64 longitude
#int32 altitude_altitudeValue

float32 latitude
float64 longitude
float32 altitude_altitudeValue

# BasicVehicleContainerHighFrequency (Simplified)

#uint16 heading_headingValue
#uint16 speed_speedValue
float32 heading_headingValue
float32 speed_speedValue

int8 driveDirection

#int16 steeringWheelAngle_steeringWheelAngleValue
float32 steeringWheelAngle_steeringWheelAngleValue

float32 gasPedalPercent_Value
float32 brakePedalPercent_Value

#float32 Ref_distance
#float32 leader_distance





