# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_its_msgs/OMNET_CAM.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class OMNET_CAM(genpy.Message):
  _md5sum = "c8e185aa09a6a67e142adbb8f653456b"
  _type = "ros_its_msgs/OMNET_CAM"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string car_name

float32 latitude
float64 longitude
float32 altitude

float32 heading
float32 speed

float32 acceleration
"""
  __slots__ = ['car_name','latitude','longitude','altitude','heading','speed','acceleration']
  _slot_types = ['string','float32','float64','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       car_name,latitude,longitude,altitude,heading,speed,acceleration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OMNET_CAM, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.car_name is None:
        self.car_name = ''
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.altitude is None:
        self.altitude = 0.
      if self.heading is None:
        self.heading = 0.
      if self.speed is None:
        self.speed = 0.
      if self.acceleration is None:
        self.acceleration = 0.
    else:
      self.car_name = ''
      self.latitude = 0.
      self.longitude = 0.
      self.altitude = 0.
      self.heading = 0.
      self.speed = 0.
      self.acceleration = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.car_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_fd4f().pack(_x.latitude, _x.longitude, _x.altitude, _x.heading, _x.speed, _x.acceleration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.car_name = str[start:end].decode('utf-8')
      else:
        self.car_name = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.latitude, _x.longitude, _x.altitude, _x.heading, _x.speed, _x.acceleration,) = _get_struct_fd4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.car_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_fd4f().pack(_x.latitude, _x.longitude, _x.altitude, _x.heading, _x.speed, _x.acceleration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.car_name = str[start:end].decode('utf-8')
      else:
        self.car_name = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.latitude, _x.longitude, _x.altitude, _x.heading, _x.speed, _x.acceleration,) = _get_struct_fd4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_fd4f = None
def _get_struct_fd4f():
    global _struct_fd4f
    if _struct_fd4f is None:
        _struct_fd4f = struct.Struct("<fd4f")
    return _struct_fd4f
